# Setup
title:        Ik-Data
tagline:      Procesamiento iInteligente de Documentos
baseurl:      "/ikdata-documentacion-spa"
paginate:     1
locale:       "es"

# About/contact
author:
  name:       IKNO-SDM
  url:        https://github.com/ikno-sdm

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown